a=input('your first number')
b=input('your second number')
c=input('your third number')
d=input('your fourth number')
e=input('your fifth number')

print('\n float of',a,'=',float(a))
print('complex of',a,'=',complex(a))
print('\n float of',b,'=',float(b))
print('complex of',b,'=',complex(b))
print('\n float of',c,'=',float(c))
print('complex of',c,'=',complex(c))
print('\n float of',d,'=',float(d))
print('complex of',d,'=',complex(d))
print('\n float of',e,'=',float(e))
print('complex of',e,'=',complex(e))